name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run the frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run the backend tests
      working-directory: ./backend
      run: npm test
    - name: Build frontend
      working-directory: ./backend
      run: npm run build
    - name: Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: "matthewpierson01@gmail.com"
    - name: Add Heroku remote
      working-directory: backend
      run: heroku git:remote --app "cise-assignment2"
    - name: Setup Heroku
      run: |
        heroku buildpacks:clear
        heroku buildpacks:add heroku/nodejs
        git push heroku main --force
