name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run the frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run the backend tests
      working-directory: ./backend
      run: npm test

    - name: Build backend
      working-directory: ./backend
      run: npm run build
    - name: Deploy
      run: |
        git config --global user.name githubActions
        git config --global user.email gnn5314@aut.ac.nz
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}

