name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run the frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run the backend tests
      working-directory: ./backend
      run: npm test
      
    - name: Deploy app to Heroku
      working-directory: ./backend
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "cise-assignment2"
            heroku_email: "matthewpierson01@gmail.com"
            appdir: "backend"
            procfile: "web:node backend/app.js"
